server:
  port: 8765
spring:
  application:
    name: api-gateway
eureka:
  instance:
    hostname: localhost
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true











